    <div class="container">
        <div class="registro-ponto">
            <form id="formulario-registro">
                <div id="data-hora">
                    <h2 id="data"></h2>
                    <h1 id="hora"></h1>
                </div>
                
                <label for="nome">Nome do Colaborador:</label>
                <select id="cargos" name="cargo" required> 
                    <option value="#">Colaborador 1</option>
                </select>

                <label for="matricula">Matrícula:</label>
                <input type="text" id="matricula" name="matricula" required readonly>

                <label for="entrada">Horário de Entrada:</label>
                <input type="time" id="entrada" name="entrada" required>

                <label for="saida">Horário de Saída:</label>
                <input type="time" id="saida" name="saida" required>

                <button type="button" id="btn-registrar" onclick="registrarPonto()">Registrar</button>
            </form>
        </div>
    </div>