    <main>
        <h1>Alterar Dados do Colaborador</h1>
        <?php foreach($this->view->colaborador as $colaborador) { ?>
        <form action="/saveEdit?matricula=<?= $colaborador['matricula'] ?>" method="post">
            <div class="box-grande">
                
                <div class="linha">
                    <div class="campo">
                        <label for="matricula">Matrícula</label>
                        <input type="text" id="matricula" name="matricula" value="<?= $colaborador['matricula'] ?>" readonly> <!-- readonly -->
                    </div>
                    <div class="campo">
                        <label for="cpf">CPF</label>
                        <input type="text" id="cpf" name="cpf" value="<?= $colaborador['cpf'] ?>" readonly> <!-- readonly -->
                    </div>
                    <div class="campo">
                        <label for="usuario">Usuário</label>
                        <input type="text" id="usuario" name="usuario" value="<?= $colaborador['usuario'] ?>" readonly> <!-- readonly -->
                    </div>
                    
                    <div class="campo">
                        <label for="ativo">Ativo?</label>
                        <input type="checkbox" id="ativo" name="ativo">  <!-- readonly -->
                    </div>
                </div>

                <div class="linha">
                    <div class="campo campo-nome">
                        <label for="nome">Nome*</label>
                        <input type="text" id="nome" name="nome" value="<?= $colaborador['nome'] ?>" required>
                    </div>
                    <div class="campo">
                        <label for="data_nascimento">Data de Nascimento*</label>
                        <input type="date" id="data_nascimento" name="data_nascimento" value="<?= $colaborador['data_nascimento'] ?>" required>
                    </div>
                    <div class="campo">
                        <label for="data_admissao">Data de Admissão*</label>
                        <input type="date" id="data_admissao" name="data_admissao" value="<?= $colaborador['data_admissao'] ?>"required>
                    </div>
                </div>

                <div class="linha">
                    <div class="campo">
                        <label for="email">Email*</label>
                        <input type="email" id="email" name="email" value="<?= $colaborador['email'] ?>" required>
                    </div>
                    <div class="campo">
                        <label for="cargos">Cargo*</label>
                        <select id="cargos" name="cargo" required>
                            <?php foreach($this->view->cargos as $cargo) { ?> 
                                <option value="<?= $cargo['id_cargo'] ?>"><?= $cargo['nome_cargo'] ?></option>
                            <?php } ?>
                        </select>
                    </div>
                </div>

                <div class="linha">
                    <div class="campo">
                        <label for="funcao">Função*</label>
                        <select id="funcao" name="funcao" required>
                            <?php foreach($this->view->funcoes as $funcao) { ?> 
                                <option value="<?= $funcao['id_funcao'] ?>"><?= $funcao['nome_funcao'] ?></option>
                            <?php } ?>
                        </select>
                    </div>
                    <div class="campo">
                        <label for="data_rescisao">Data de Rescisão</label>
                        <input type="date" id="data_rescisao" name="data_rescisao" value="<?= $colaborador['data_rescisao'] ?>">
                    </div>
                </div>

                <div class="linha">
                    <label for="horarios">Horários</label>
                    <table>
                        <thead>
                            <tr>
                                <th></th>
                                <th>Segunda</th>
                                <th>Terça</th>
                                <th>Quarta</th>
                                <th>Quinta</th>
                                <th>Sexta</th>
                                <th>Sábado</th>
                                <th>Domingo</th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr>
                                <td>Entrada</td>
                                <td><input type="time" name="segunda_entrada" value="<?= $colaborador['segunda_entrada'] ?>"></td>
                                <td><input type="time" name="terca_entrada" value="<?= $colaborador['terca_entrada'] ?>"></td>
                                <td><input type="time" name="quarta_entrada" value="<?= $colaborador['quarta_entrada'] ?>"></td>
                                <td><input type="time" name="quinta_entrada" value="<?= $colaborador['quinta_entrada'] ?>"></td>
                                <td><input type="time" name="sexta_entrada" value="<?= $colaborador['sexta_entrada'] ?>"></td>
                                <td><input type="time" name="sabado_entrada" value="<?= $colaborador['sabado_entrada'] ?>"></td>
                                <td><input type="time" name="domingo_entrada" value="<?= $colaborador['domingo_entrada'] ?>"></td>
                            </tr>
                            <tr>
                                <td>Saída</td>
                                <td><input type="time" name="segunda_saida" value="<?= $colaborador['segunda_saida'] ?>"></td>
                                <td><input type="time" name="terca_saida" value="<?= $colaborador['terca_saida'] ?>"></td>
                                <td><input type="time" name="quarta_saida" value="<?= $colaborador['quarta_saida'] ?>"></td>
                                <td><input type="time" name="quinta_saida" value="<?= $colaborador['quinta_saida'] ?>"></td>
                                <td><input type="time" name="sexta_saida" value="<?= $colaborador['sexta_saida'] ?>"></td>
                                <td><input type="time" name="sabado_saida" value="<?= $colaborador['sabado_saida'] ?>"></td>
                                <td><input type="time" name="domingo_saida" value="<?= $colaborador['domingo_saida'] ?>"></td>
                            </tr>
                            <tr>
                                <td>Entrada</td>
                                <td><input type="time" name="s_segunda_entrada" value="<?= $colaborador['s_segunda_entrada'] ?>"></td>
                                <td><input type="time" name="s_terca_entrada" value="<?= $colaborador['s_terca_entrada'] ?>"></td>
                                <td><input type="time" name="s_quarta_entrada" value="<?= $colaborador['s_quarta_entrada'] ?>"></td>
                                <td><input type="time" name="s_quinta_entrada" value="<?= $colaborador['s_quinta_entrada'] ?>"></td>
                                <td><input type="time" name="s_sexta_entrada" value="<?= $colaborador['s_sexta_entrada'] ?>"></td>
                                <td><input type="time" name="s_sabado_entrada" value="<?= $colaborador['s_sabado_entrada'] ?>"></td>
                                <td><input type="time" name="s_domingo_entrada" value="<?= $colaborador['s_domingo_entrada'] ?>"></td>
                            </tr>
                            <tr>
                                <td>Saída</td>
                                <td><input type="time" name="s_segunda_saida" value="<?= $colaborador['s_segunda_saida'] ?>"></td>
                                <td><input type="time" name="s_terca_saida" value="<?= $colaborador['s_terca_saida'] ?>"></td>
                                <td><input type="time" name="s_quarta_saida" value="<?= $colaborador['s_quarta_saida'] ?>"></td>
                                <td><input type="time" name="s_quinta_saida" value="<?= $colaborador['s_quinta_saida'] ?>"></td>
                                <td><input type="time" name="s_sexta_saida" value="<?= $colaborador['s_sexta_saida'] ?>"></td>
                                <td><input type="time" name="s_sabado_saida" value="<?= $colaborador['s_sabado_saida'] ?>"></td>
                                <td><input type="time" name="s_domingo_saida" value="<?= $colaborador['s_domingo_saida'] ?>"></td>
                            </tr>
                        </tbody>
                    </table>
                    <?php } ?>
                </div>

                <button type="submit">Alterar Registro</button>
                <a class="btn-voltar" href="/lista">Voltar</a>
            </div>

        </form>
    </main>