    <main>
        <h1>Inserir Colaborador</h1>
        <div id="mensagem"></div>
        <form id="colaboradorForm" action="/inserir" method="post">
            <div class="box-grande">

                <div class="linha">
                    <div class="campo">
                        <label for="cpf">CPF*</label>
                        <input type="text" id="cpf" name="cpf" required>
                    </div>
                    <div class="campo">
                        <label for="ativo">Ativo?</label>
                        <input type="checkbox" id="checkboxAtivo" name="ativo" checked readonly>  <!-- readonly -->
                    </div>
                </div>

                <div class="linha">
                    <div class="campo campo-nome">
                        <label for="nome">Nome*</label>
                        <input type="text" id="nome" name="nome" required>
                    </div>
                    <div class="campo">
                        <label for="data_nascimento">Data de Nascimento*</label>
                        <input type="date" id="data_nascimento" name="data_nascimento" required>
                    </div>
                    <div class="campo">
                        <label for="data_admissao">Data de Admissão*</label>
                        <input type="date" id="data_admissao" name="data_admissao" required>
                    </div>
                </div>

                <div class="linha">
                    <div class="campo">
                        <label for="email">Email*</label>
                        <input type="email" id="email" name="email" required>
                        <?php if($this->view->verificaEmail) { ?>
                            <small style="color: red;">Este formato de email é inválido.</small>
                        <?php } ?> 
                    </div>
                    <div class="campo">
                        <label for="cargos">Cargo*</label> 
                        <select id="cargos" name="cargo" required>
                            <?php foreach($this->view->cargos as $cargo) { ?> 
                                <option value="<?= $cargo['id_cargo'] ?>"><?= $cargo['nome_cargo'] ?></option>
                            <?php } ?>
                        </select>
                    </div>
                </div>

                <div class="linha">
                    <div class="campo">
                        <label for="funcao">Função*</label>
                        <select id="funcao" name="funcao" required>
                            <?php foreach($this->view->funcoes as $funcao) { ?> 
                                <option value="<?= $funcao['id_funcao'] ?>"><?= $funcao['nome_funcao'] ?></option>
                            <?php } ?>
                        </select>
                    </div>
                    <div class="campo">
                        <label for="data_rescisao">Data de Rescisão:</label>
                        <input type="date" id="data_rescisao" name="data_rescisao">
                    </div>
                    <div class="campo">
                        <label for="usuario">Usuário*</label> 
                        <input type="text" id="usuario" name="usuario" readonly> <!-- readonly -->
                    </div>
                </div>

                <div class="linha">
                    <label for="horarios">Horários</label>
                    <table id="tabelaHorarios">
                        <thead>
                            <tr>
                                <th></th>
                                <th>Segunda</th>
                                <th>Terça</th>
                                <th>Quarta</th>
                                <th>Quinta</th>
                                <th>Sexta</th>
                                <th>Sábado</th>
                                <th>Domingo</th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr>
                                <td>Entrada</td>
                                <td><input type="time" name="segunda_entrada"></td>
                                <td><input type="time" name="terca_entrada"></td>
                                <td><input type="time" name="quarta_entrada"></td>
                                <td><input type="time" name="quinta_entrada"></td>
                                <td><input type="time" name="sexta_entrada"></td>
                                <td><input type="time" name="sabado_entrada"></td>
                                <td><input type="time" name="domingo_entrada"></td>
                            </tr>
                            <tr>
                                <td>Saída</td>
                                <td><input type="time" name="segunda_saida"></td>
                                <td><input type="time" name="terca_saida"></td>
                                <td><input type="time" name="quarta_saida"></td>
                                <td><input type="time" name="quinta_saida"></td>
                                <td><input type="time" name="sexta_saida"></td>
                                <td><input type="time" name="sabado_saida"></td>
                                <td><input type="time" name="domingo_saida"></td>
                            </tr>
                            <tr>
                                <td>Entrada</td>
                                <td><input type="time" name="s_segunda_entrada"></td>
                                <td><input type="time" name="s_terca_entrada"></td>
                                <td><input type="time" name="s_quarta_entrada"></td>
                                <td><input type="time" name="s_quinta_entrada"></td>
                                <td><input type="time" name="s_sexta_entrada"></td>
                                <td><input type="time" name="s_sabado_entrada"></td>
                                <td><input type="time" name="s_domingo_entrada"></td>
                            </tr>
                            <tr>
                                <td>Saída</td>
                                <td><input type="time" name="s_segunda_saida"></td>
                                <td><input type="time" name="s_terca_saida"></td>
                                <td><input type="time" name="s_quarta_saida"></td>
                                <td><input type="time" name="s_quinta_saida"></td>
                                <td><input type="time" name="s_sexta_saida"></td>
                                <td><input type="time" name="s_sabado_saida"></td>
                                <td><input type="time" name="s_domingo_saida"></td>
                            </tr>
                        </tbody>
                    </table>
                </div>

                <button type="submit"><i class="fas fa-save"></i>Inserir Registro</button>
                <a class="btn-voltar" href="/lista">Voltar</a>
            </div>

        </form>
    </main>