<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Gestão de Colaboradores</title>

    <link rel="stylesheet" href="/css/style2.css">
</head>
<body>
    <div class="nav">
        <header>
            <div class="logo">
                <a href="/"><img src="/img/Marca FIESC (1).jpg" alt=""></a>
            </div>
            <nav>
                <ul>
                    <li><a href="/"><b>Página Inicial</b></a></li>
                    <li><a href="/login"><b>Login</b></a></li>
                </ul>
            </nav>
        </header>
    </div>

    <?= $this->content() ?>

    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css" integrity="sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.6.4.min.js"></script>
    <script type="text/javascript" src="/js/script.js"></script>
</body>
</html>